---
title: "Association between Economic Ideology and Racial Resentment"
output:
  pdf_document: default
  html_document: default
---

*A cross-national comparison, adjusted for educational attainment and relgious service attendance*

*Higher coefficients indicate a stronger association between right-wing economic ideology and higher levels of racial resentment (and between left-wing economic ideology and lower levels of racial resentment)*

*Method: Ordinal logistic regression*

```{r code, include=FALSE}
# Load packages & data

library(shiny)
library(ggplot2)
library(tidyverse)
library(ggrepel)
library(survey)
library(rvest)
library(plyr)
library(broom)
library(knitr)
library(RCurl)
library(stargazer)
library(reshape2)
library(gridExtra)
library(ggiraph)
library(colorspace)
library(MASS)
library(lubridate)

url <- getURL("https://raw.githubusercontent.com/jordan-klein/internationalLeft/master/W_EVS_clean.csv")
W_EVS <- read.csv(text = url)

W_EVS <- W_EVS %>% mutate(RacRes = factor(RacRes, levels = c("Very low", "Low", "Moderate", "High", "Very high")))

cw_list <- W_EVS %>% dlply('country_wave')

# Create coefficient matrix

lapply(cw_list, function(x) {
  filter(x, !is.na(RacRes) & !is.na(ec_ideo) & !is.na(edu) & !is.na(relig))
}) %>% 
  .[sapply(., function(x) {
    dim(x)[1] > 0
  })] %>% 
  lapply(function(x) {
    model <- polr(RacRes ~ ec_ideo + edu + relig, data = x, weights = S017, Hess = T)
    return(data.frame(rac_ec_adj = model$coefficients[1]))
  }) %>% 
  do.call(rbind.data.frame, .) %>% 
  data.frame(country_wave = row.names(.), .) -> rac_ec_adj

combined_adj <- sort(union(levels(W_EVS$country_wave), levels(rac_ec_adj$country_wave)))

left_join(mutate(rac_ec_adj, country_wave = factor(country_wave, levels = combined_adj)), 
          mutate(unique(dplyr::select(W_EVS, country_wave, country, S020)), 
                 country_wave = factor(country_wave, levels = combined_adj))) -> rac_ec_adj

rac_ec_adj %>% mutate(S020 = as.Date(ISOdate(S020, 1, 1))) %>% 
  mutate(country = droplevels(country)) -> rac_ec_adj

names(rac_ec_adj)[2] <- "Coefficients"

names(rac_ec_adj)[1] <- "`Country & survey year`"

POLR.tab <- rac_ec_adj[order(rac_ec_adj$Coefficients, decreasing = T), c(1:2)]
```

```{r echo=FALSE, results='asis'}
kable(POLR.tab, row.names = F)
```
